x-service-base: &service-base
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  networks:
    - red

services:
  gateway:
    <<: *service-base
    build:
      args:
        COPY_REQUIREMENTS: "false"
        SERVICE_PATH: .
        SERVICE_PORT: ${SERVICE_GATEWAY_PORT}
    container_name: gateway
    ports:
      - ${SERVICE_GATEWAY_PORT}:${SERVICE_GATEWAY_PORT}

  wikis:
    <<: *service-base
    build:
      args:
        SERVICE_PATH: services/wikis
        SERVICE_PORT: ${SERVICE_WIKIS_PORT}
    container_name: wikis
    ports:
      - ${SERVICE_WIKIS_PORT}:${SERVICE_WIKIS_PORT}

  entradas-versiones:
    <<: *service-base
    build:
      args:
        SERVICE_PATH: services/entradas_versiones
        SERVICE_PORT: ${SERVICE_ENTRADAS_PORT}
    container_name: entradas_versiones
    ports:
      - ${SERVICE_ENTRADAS_PORT}:${SERVICE_ENTRADAS_PORT}

  comentarios-valoraciones:
    <<: *service-base
    build:
      args:
        SERVICE_PATH: services/comentarios_valoraciones
        SERVICE_PORT: ${SERVICE_COMENTARIOS_PORT}
    container_name: comentarios_valoraciones
    ports:
      - ${SERVICE_COMENTARIOS_PORT}:${SERVICE_COMENTARIOS_PORT}

networks:
  red:
    driver: bridge