services:
  entradas-versiones:
    build:
      context: .
      dockerfile: services/entradas-versiones/Dockerfile
    container_name: entradas_versiones_service
    env_file:
      - .env
    ports:
      - 5001:5000