services:
  wikis:
    build:
      context: .
      dockerfile: services/wikis/Dockerfile
    container_name: wikis
    env_file:
      - .env
    networks:
      - red
    ports:
      - 5000:5000

  entradas-versiones:
    build:
      context: .
      dockerfile: services/entradas_versiones/Dockerfile
    container_name: entradas_versiones
    env_file:
      - .env
    networks:
      - red
    ports:
      - 5001:5001

  comentarios-valoraciones:
    build:
      context: .
      dockerfile: services/comentarios_valoraciones/Dockerfile
    container_name: comentarios_valoraciones
    env_file:
      - .env
    networks:
      - red
    ports:
      - 5002:5002

networks:
  red:
    driver: bridge