services:
  entradas-versiones:
    build:
      context: .
      dockerfile: services/entradas-versiones/Dockerfile
    container_name: entradas_versiones
    env_file:
      - .env
    networks:
      - red
    ports:
      - 5001:5000

networks:
  red:
    driver: bridge