openapi: 3.0.3
info:
  title: laWiki API
  version: 1.0.0
  description: API para gestionar entradas y comentarios en laWiki.

paths:
  /entradas:
    get:
      summary: Obtener entradas
      description: Devuelve todas las entradas o filtra por título.
      parameters:
        - name: titulo
          in: query
          required: false
          schema:
            type: string
          description: Título para filtrar entradas por similitud.
      responses:
        '200':
          description: Lista de entradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entrada'

    post:
      summary: Crear una nueva entrada
      description: Crea una entrada en la colección de entradas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entrada'
      responses:
        '201':
          description: Entrada creada correctamente

    delete:
      summary: Eliminar una entrada
      description: Elimina una entrada específica enviando los datos en el cuerpo de la solicitud.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entrada'
      responses:
        '200':
          description: Entrada eliminada correctamente
        '404':
          description: Entrada no encontrada

  /entradas/{nombreEntrada}:
    put:
      summary: Actualizar una entrada
      description: Actualiza una entrada según el nombre.
      parameters:
        - name: nombreEntrada
          in: path
          required: true
          schema:
            type: string
          description: Nombre de la entrada a actualizar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entrada'
      responses:
        '200':
          description: Entrada actualizada correctamente
        '404':
          description: Entrada no encontrada

  /entradas/{slug}/comments:
    get:
      summary: Obtener comentarios de una entrada
      description: Obtiene todos los comentarios para una entrada específica por su slug.
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: Slug de la entrada.
      responses:
        '200':
          description: Lista de comentarios de la entrada
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comentario'

    post:
      summary: Crear un comentario en una entrada
      description: Añade un comentario a una entrada específica.
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: Slug de la entrada.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comentario'
      responses:
        '201':
          description: Comentario creado correctamente

    delete:
      summary: Eliminar un comentario
      description: Elimina un comentario de una entrada específica usando el ID del comentario.
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: Slug de la entrada.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID del comentario a eliminar.
      responses:
        '200':
          description: Comentario eliminado correctamente
        '404':
          description: Comentario no encontrado

    put:
      summary: Actualizar un comentario
      description: Actualiza un comentario en una entrada específica.
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: Slug de la entrada.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID del comentario a actualizar.
                contenido:
                  type: string
                  description: Nuevo contenido del comentario.
      responses:
        '200':
          description: Comentario actualizado correctamente
        '404':
          description: Comentario no encontrado

components:
  schemas:
    Entrada:
      type: object
      properties:
        nombreEntrada:
          type: string
          description: Nombre de la entrada.
        slug:
          type: string
          description: Slug generado a partir del nombre de la entrada.

    Comentario:
      type: object
      properties:
        id:
          type: string
          description: ID del comentario.
        contenido:
          type: string
          description: Contenido del comentario.
        idEntrada:
          type: string
          description: ID de la entrada asociada al comentario.
